# Sample Airline Information Data

To run our optimization model and evaluate its performance, we need to compare the results against actual data. In this project, we will use information from Allegiant Airlines, which includes their flight routes, fleet information, and historical profit data.

In [58]:
import pandas as pd

In [59]:
allegiant_df = pd.read_csv("../data/allegiant_routes_info.csv")
display(allegiant_df.head())

   distance airport_1 airport_2
0      1342       AUS       IAD
1      1340       AUS       IAD
2       587       BNA       IAD
3       588       BNA       IAD
4       612       BNA       PIE

In [60]:
# Load historical flight data that has been preprocessed
historical_df = pd.read_csv("../data/cleaned_data.csv")
# First aggregate historical_df to get unique airport pairs
unique_routes_df = historical_df.groupby(['airport_1', 'airport_2']).agg({
    'state_1': 'first',
    'city_1': 'first',
    'state_2': 'first',
    'city_2': 'first',
    'population_1': 'mean',
    'density_1': 'mean',
    'population_2': 'mean',
    'density_2': 'mean',
    'lat_1': 'first',
    'lon_1': 'first',
    'lat_2': 'first',
    'lon_2': 'first'
}).reset_index()
print("There are a total of", unique_routes_df.shape[0], "unique routes.")

There are a total of 4067 unique routes.

In [61]:
# Merge the dataframes on airport_1 and airport_2
merged_df = pd.merge(
    allegiant_df,
    unique_routes_df,
    on=['airport_1', 'airport_2'],
    how='left'  # Use 'left' to keep all rows from df
)

# Display the merged dataframe
display(merged_df.head())

,distance,airport_1,airport_2,state_1,city_1,state_2,city_2,population_1,density_1,population_2,density_2,lat_1,lon_1,lat_2,lon_2
0,1342,AUS,IAD,TX,Austin,DC,Washington,1905945.0,1154.1,5116378.0,4235.7,30.264979,-97.746598,38.892062,-77.019912
1,1340,AUS,IAD,TX,Austin,DC,Washington,1905945.0,1154.1,5116378.0,4235.7,30.264979,-97.746598,38.892062,-77.019912
2,587,BNA,IAD,TN,Nashville,DC,Washington,1177657.0,555.4,5116378.0,4235.7,36.166687,-86.779932,38.892062,-77.019912
3,588,BNA,IAD,TN,Nashville,DC,Washington,1177657.0,555.4,5116378.0,4235.7,36.166687,-86.779932,38.892062,-77.019912
4,612,BNA,PIE,TN,Nashville,FL,Tampa,1177657.0,555.4,2861173.0,1320.9,36.166687,-86.779932,37.860600,-78.804199

In [62]:
# Verify the number of rows is unchanged
print(f"Original df rows: {len(df)}")
print(f"Merged df rows: {len(merged_df)}")

Original df rows: 321
Merged df rows: 321

In [63]:
merged_df.to_csv("../data/allegiant_routes_info_transformed.csv", index=False)